apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: vlemt1d96-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/vlemt1d96-dotnet-basic-gitops